export type CoreWord = readonly [english: string, german: string];

// A practical A1–B1 core vocabulary. Kept as compact tuples so the list is
// easy to review and does not inflate the client bundle with repeated keys.
export const coreWords: CoreWord[] = [
  ["the", "der, die, das"], ["be", "sein"], ["to", "zu, nach"], ["of", "von"], ["and", "und"],
  ["a", "ein, eine"], ["in", "in"], ["that", "das, dass"], ["have", "haben"], ["I", "ich"],
  ["it", "es"], ["for", "für"], ["not", "nicht"], ["on", "auf, an"], ["with", "mit"],
  ["he", "er"], ["as", "als, wie"], ["you", "du, Sie, ihr"], ["do", "tun, machen"], ["at", "an, bei"],
  ["this", "dies, dieses"], ["but", "aber"], ["his", "sein"], ["by", "von, durch"], ["from", "von, aus"],
  ["they", "sie"], ["we", "wir"], ["say", "sagen"], ["her", "ihr, sie"], ["she", "sie"],
  ["or", "oder"], ["an", "ein, eine"], ["will", "werden"], ["my", "mein"], ["one", "eins, man"],
  ["all", "alle, alles"], ["would", "würde"], ["there", "dort, da"], ["their", "ihr"], ["what", "was"],
  ["so", "so, also"], ["up", "hinauf, oben"], ["out", "hinaus, draußen"], ["if", "wenn, falls"], ["about", "über, ungefähr"],
  ["who", "wer"], ["get", "bekommen, werden"], ["which", "welcher, welche"], ["go", "gehen, fahren"], ["me", "mich, mir"],
  ["when", "wann, wenn"], ["make", "machen, herstellen"], ["can", "können"], ["like", "mögen, wie"], ["time", "Zeit"],
  ["no", "nein, kein"], ["just", "gerade, nur"], ["him", "ihn, ihm"], ["know", "wissen, kennen"], ["take", "nehmen"],
  ["people", "Menschen, Leute"], ["into", "in, hinein"], ["year", "Jahr"], ["your", "dein, Ihr"], ["good", "gut"],
  ["some", "einige, etwas"], ["could", "könnte"], ["them", "sie, ihnen"], ["see", "sehen"], ["other", "andere"],
  ["than", "als"], ["then", "dann"], ["now", "jetzt"], ["look", "schauen, aussehen"], ["only", "nur"],
  ["come", "kommen"], ["its", "sein, dessen"], ["over", "über, vorbei"], ["think", "denken"], ["also", "auch"],
  ["back", "zurück, Rücken"], ["after", "nach"], ["use", "benutzen, Verwendung"], ["two", "zwei"], ["how", "wie"],
  ["our", "unser"], ["work", "arbeiten, Arbeit"], ["first", "erste, zuerst"], ["well", "gut, nun"], ["way", "Weg, Art"],
  ["even", "sogar, gerade"], ["new", "neu"], ["want", "wollen"], ["because", "weil"], ["these", "diese"],
  ["give", "geben"], ["day", "Tag"], ["most", "die meisten, am meisten"], ["us", "uns"], ["is", "ist"],
  ["are", "sind"], ["was", "war"], ["were", "waren"], ["been", "gewesen"], ["has", "hat"],
  ["had", "hatte"], ["did", "tat, machte"], ["may", "dürfen, könnte"], ["should", "sollte"], ["must", "müssen"],
  ["very", "sehr"], ["many", "viele"], ["much", "viel"], ["more", "mehr"], ["any", "irgendein, etwas"],
  ["each", "jede, jeder"], ["every", "jede, jeder"], ["both", "beide"], ["few", "wenige"], ["another", "ein weiterer"],
  ["same", "gleich, derselbe"], ["own", "eigen"], ["such", "solch"], ["again", "wieder"], ["still", "noch, immer noch"],
  ["here", "hier"], ["where", "wo"], ["why", "warum"], ["while", "während"], ["before", "vor, bevor"],
  ["through", "durch"], ["between", "zwischen"], ["under", "unter"], ["around", "um, herum"], ["against", "gegen"],
  ["without", "ohne"], ["during", "während"], ["off", "aus, weg"], ["down", "hinunter, unten"], ["away", "weg"],
  ["always", "immer"], ["often", "oft"], ["sometimes", "manchmal"], ["never", "nie"], ["today", "heute"],
  ["tomorrow", "morgen"], ["yesterday", "gestern"], ["already", "bereits"], ["soon", "bald"], ["later", "später"],
  ["early", "früh"], ["late", "spät"], ["long", "lang"], ["little", "klein, wenig"], ["right", "richtig, rechts"],
  ["left", "links, übrig"], ["big", "groß"], ["small", "klein"], ["high", "hoch"], ["low", "niedrig"],
  ["old", "alt"], ["young", "jung"], ["important", "wichtig"], ["different", "verschieden"], ["easy", "einfach"],
  ["hard", "schwer, hart"], ["great", "großartig"], ["bad", "schlecht"], ["better", "besser"], ["best", "beste"],
  ["sure", "sicher"], ["possible", "möglich"], ["able", "fähig"], ["real", "echt, wirklich"], ["true", "wahr"],
  ["free", "frei, kostenlos"], ["full", "voll"], ["open", "offen, öffnen"], ["close", "schließen, nah"], ["ready", "bereit"],
  ["happy", "glücklich"], ["sad", "traurig"], ["afraid", "ängstlich"], ["tired", "müde"], ["busy", "beschäftigt"],
  ["beautiful", "schön"], ["strong", "stark"], ["kind", "freundlich, Art"], ["clear", "klar"], ["enough", "genug"],
  ["man", "Mann"], ["woman", "Frau"], ["child", "Kind"], ["children", "Kinder"], ["family", "Familie"],
  ["friend", "Freund, Freundin"], ["mother", "Mutter"], ["father", "Vater"], ["brother", "Bruder"], ["sister", "Schwester"],
  ["name", "Name"], ["home", "Zuhause"], ["house", "Haus"], ["room", "Zimmer"], ["door", "Tür"],
  ["window", "Fenster"], ["place", "Ort, Platz"], ["world", "Welt"], ["country", "Land"], ["city", "Stadt"],
  ["street", "Straße"], ["school", "Schule"], ["student", "Schüler, Student"], ["teacher", "Lehrer, Lehrerin"], ["job", "Beruf, Arbeit"],
  ["company", "Firma"], ["business", "Geschäft, Unternehmen"], ["office", "Büro"], ["money", "Geld"], ["price", "Preis"],
  ["shop", "Geschäft, einkaufen"], ["market", "Markt"], ["food", "Essen, Lebensmittel"], ["water", "Wasser"], ["coffee", "Kaffee"],
  ["tea", "Tee"], ["bread", "Brot"], ["milk", "Milch"], ["fruit", "Obst"], ["vegetable", "Gemüse"],
  ["breakfast", "Frühstück"], ["lunch", "Mittagessen"], ["dinner", "Abendessen"], ["car", "Auto"], ["bus", "Bus"],
  ["train", "Zug"], ["road", "Straße, Weg"], ["travel", "reisen, Reise"], ["trip", "Reise, Ausflug"], ["holiday", "Ferien, Urlaub"],
  ["hotel", "Hotel"], ["airport", "Flughafen"], ["ticket", "Fahrkarte, Ticket"], ["book", "Buch, buchen"], ["table", "Tisch"],
  ["chair", "Stuhl"], ["bed", "Bett"], ["phone", "Telefon"], ["computer", "Computer"], ["internet", "Internet"],
  ["email", "E-Mail"], ["picture", "Bild"], ["music", "Musik"], ["film", "Film"], ["game", "Spiel"],
  ["question", "Frage"], ["answer", "Antwort"], ["idea", "Idee"], ["problem", "Problem"], ["reason", "Grund"],
  ["story", "Geschichte"], ["word", "Wort"], ["language", "Sprache"], ["number", "Zahl, Nummer"], ["part", "Teil"],
  ["thing", "Ding, Sache"], ["life", "Leben"], ["hand", "Hand"], ["head", "Kopf"], ["face", "Gesicht"],
  ["eye", "Auge"], ["body", "Körper"], ["health", "Gesundheit"], ["doctor", "Arzt, Ärztin"], ["night", "Nacht"],
  ["morning", "Morgen"], ["evening", "Abend"], ["week", "Woche"], ["month", "Monat"], ["hour", "Stunde"],
  ["minute", "Minute"], ["moment", "Moment"], ["beginning", "Anfang"], ["end", "Ende"], ["age", "Alter"],
  ["find", "finden"], ["tell", "erzählen, sagen"], ["ask", "fragen"], ["feel", "fühlen"], ["try", "versuchen"],
  ["leave", "verlassen"], ["call", "anrufen, nennen"], ["keep", "behalten"], ["let", "lassen"], ["begin", "beginnen"],
  ["seem", "scheinen"], ["help", "helfen, Hilfe"], ["talk", "reden"], ["turn", "drehen, abbiegen"], ["start", "anfangen"],
  ["show", "zeigen"], ["hear", "hören"], ["play", "spielen"], ["run", "laufen"], ["move", "bewegen, umziehen"],
  ["live", "leben, wohnen"], ["believe", "glauben"], ["bring", "bringen"], ["happen", "geschehen"], ["write", "schreiben"],
  ["provide", "bereitstellen"], ["sit", "sitzen"], ["stand", "stehen"], ["lose", "verlieren"], ["pay", "bezahlen"],
  ["meet", "treffen"], ["include", "enthalten"], ["continue", "fortsetzen"], ["set", "setzen, einstellen"], ["learn", "lernen"],
  ["change", "ändern, Veränderung"], ["lead", "führen"], ["understand", "verstehen"], ["watch", "ansehen, Uhr"], ["follow", "folgen"],
  ["stop", "anhalten"], ["create", "erschaffen"], ["speak", "sprechen"], ["read", "lesen"], ["allow", "erlauben"],
  ["add", "hinzufügen"], ["spend", "ausgeben, verbringen"], ["grow", "wachsen"], ["walk", "gehen, spazieren"], ["win", "gewinnen"],
  ["offer", "anbieten"], ["remember", "sich erinnern"], ["love", "lieben, Liebe"], ["consider", "betrachten, überlegen"], ["appear", "erscheinen"],
  ["buy", "kaufen"], ["wait", "warten"], ["serve", "dienen, bedienen"], ["die", "sterben"], ["send", "senden"],
  ["expect", "erwarten"], ["build", "bauen"], ["stay", "bleiben"], ["fall", "fallen"], ["cut", "schneiden"],
  ["reach", "erreichen"], ["eat", "essen"], ["drink", "trinken"], ["sleep", "schlafen"], ["drive", "fahren"],
  ["choose", "wählen"], ["wear", "tragen"], ["wash", "waschen"], ["cook", "kochen"], ["need", "brauchen"],
  ["become", "werden"], ["put", "legen, stellen"], ["mean", "bedeuten"], ["return", "zurückkehren"], ["explain", "erklären"],
  ["hope", "hoffen"], ["decide", "entscheiden"], ["carry", "tragen"], ["break", "brechen, Pause"], ["receive", "erhalten"],
  ["agree", "zustimmen"], ["sell", "verkaufen"], ["pass", "vorbeigehen, bestehen"], ["forget", "vergessen"], ["listen", "zuhören"],
  ["person", "Person"], ["group", "Gruppe"], ["team", "Team"], ["parent", "Elternteil"], ["baby", "Baby"],
  ["boy", "Junge"], ["girl", "Mädchen"], ["neighbor", "Nachbar, Nachbarin"], ["customer", "Kunde, Kundin"], ["police", "Polizei"],
  ["information", "Information"], ["news", "Nachrichten"], ["example", "Beispiel"], ["fact", "Tatsache"], ["point", "Punkt"],
  ["side", "Seite"], ["line", "Linie, Zeile"], ["area", "Gebiet, Bereich"], ["center", "Mitte, Zentrum"], ["level", "Niveau, Ebene"],
  ["result", "Ergebnis"], ["service", "Dienstleistung"], ["plan", "Plan"], ["project", "Projekt"], ["program", "Programm"],
  ["course", "Kurs"], ["test", "Test"], ["paper", "Papier"], ["letter", "Brief, Buchstabe"], ["map", "Karte"],
  ["color", "Farbe"], ["light", "Licht, leicht"], ["air", "Luft"], ["fire", "Feuer"], ["earth", "Erde"],
  ["weather", "Wetter"], ["rain", "Regen"], ["sun", "Sonne"], ["tree", "Baum"], ["animal", "Tier"],
  ["dog", "Hund"], ["cat", "Katze"], ["garden", "Garten"], ["date", "Datum, Verabredung"], ["season", "Jahreszeit"],
  ["spring", "Frühling"], ["summer", "Sommer"], ["autumn", "Herbst"], ["winter", "Winter"], ["north", "Norden"],
  ["south", "Süden"], ["east", "Osten"], ["west", "Westen"], ["inside", "drinnen"], ["outside", "draußen"],
  ["above", "über, oberhalb"], ["below", "unter, unterhalb"], ["near", "nah"], ["far", "weit"], ["together", "zusammen"],
  ["maybe", "vielleicht"], ["really", "wirklich"], ["almost", "fast"], ["especially", "besonders"], ["probably", "wahrscheinlich"],
  ["usually", "gewöhnlich"], ["quickly", "schnell"], ["slowly", "langsam"], ["carefully", "vorsichtig"], ["exactly", "genau"],
  ["yes", "ja"], ["please", "bitte"], ["thanks", "danke"], ["sorry", "Entschuldigung"], ["hello", "hallo"],
  ["goodbye", "auf Wiedersehen"], ["red", "rot"], ["blue", "blau"], ["green", "grün"], ["black", "schwarz"],
  ["white", "weiß"], ["hot", "heiß"], ["cold", "kalt"], ["warm", "warm"], ["clean", "sauber"],
  ["dirty", "schmutzig"], ["fast", "schnell"], ["slow", "langsam"], ["cheap", "günstig"], ["expensive", "teuer"],
  ["rich", "reich"], ["poor", "arm"], ["safe", "sicher"], ["dangerous", "gefährlich"], ["healthy", "gesund"],
  ["sick", "krank"], ["hungry", "hungrig"], ["thirsty", "durstig"], ["interesting", "interessant"], ["boring", "langweilig"],
  ["nice", "nett, schön"], ["friendly", "freundlich"], ["quiet", "ruhig"], ["loud", "laut"], ["correct", "korrekt"],
  ["wrong", "falsch"], ["single", "einzeln, ledig"], ["married", "verheiratet"], ["special", "besonders"], ["normal", "normal"],
  ["public", "öffentlich"], ["private", "privat"], ["available", "verfügbar"], ["necessary", "notwendig"], ["certain", "sicher, bestimmt"],
  ["three", "drei"], ["four", "vier"], ["five", "fünf"], ["six", "sechs"], ["seven", "sieben"],
  ["eight", "acht"], ["nine", "neun"], ["ten", "zehn"], ["eleven", "elf"], ["twelve", "zwölf"],
];
