// Simple A1–B1 examples in the same order as coreWords.
export const coreExamples: readonly string[] = [
  // 0–49
  "The book is on the table.", "I want to be ready.", "We walk to school.", "The door of the house is open.", "Tom and Mia are friends.",
  "I have a new bag.", "She lives in London.", "I know that answer.", "We have enough time.", "I like this song.",
  "It is very cold today.", "This gift is for you.", "I am not tired.", "The keys are on the desk.", "Come with me, please.",
  "He works in an office.", "It is as big as mine.", "You can sit here.", "They do their homework.", "Meet me at the station.",
  "This is my room.", "I called, but nobody answered.", "His car is blue.", "We travelled by train.", "She comes from Spain.",
  "They live near the school.", "We are ready to go.", "Please say your name.", "I gave her the book.", "She speaks English well.",
  "Would you like tea or coffee?", "He bought an apple.", "I will call you tomorrow.", "My phone is in my bag.", "One student is absent.",
  "All the windows are open.", "I would like some water.", "There is a café nearby.", "Their house has a garden.", "What is your name?",
  "It was late, so we left.", "Please look up at the sky.", "She went out with friends.", "Call me if you need help.", "We talked about the film.",
  "Who is at the door?", "I usually get home at six.", "Which colour do you prefer?", "I go to work by bus.", "Please wait for me.",
  // 50–99
  "When does the train leave?", "Can you make some coffee?", "I can help you.", "I like Italian food.", "We have time for lunch.",
  "No, I do not agree.", "I am just looking.", "I saw him yesterday.", "Do you know the answer?", "Please take a seat.",
  "Many people work here.", "Come into the room.", "She lived there for a year.", "Is this your coat?", "The food tastes good.",
  "Would you like some tea?", "We could meet tomorrow.", "I spoke to them after work.", "I can see the mountains.", "Do you have any other questions?",
  "This one is bigger than that one.", "Finish your work, then come home.", "We need to leave now.", "Look at this picture.", "I only need five minutes.",
  "Please come inside.", "The dog hurt its leg.", "The meeting is over.", "I think you are right.", "She also speaks French.",
  "I will be back soon.", "We went home after dinner.", "You can use my phone.", "I have two sisters.", "How are you today?",
  "Our house is near the station.", "I start work at eight.", "She was the first person there.", "I do not feel well.", "This is the best way home.",
  "Even children understand it.", "I bought a new jacket.", "I want a cup of tea.", "We stayed home because it rained.", "These shoes are very comfortable.",
  "Please give me the key.", "It was a beautiful day.", "Most people arrived early.", "Can you help us?", "The shop is open.",
  // 100–149
  "The children are outside.", "The weather was warm yesterday.", "We were very busy.", "I have been to Paris.", "She has a new job.",
  "They had lunch together.", "He did the work alone.", "It may rain this evening.", "You should drink more water.", "We must leave now.",
  "The film was very interesting.", "Many students take the bus.", "We do not have much time.", "Would you like more coffee?", "Do you have any questions?",
  "Each student has a book.", "I walk here every day.", "Both answers are correct.", "Only a few people knew.", "Can I have another cup?",
  "We chose the same colour.", "She has her own office.", "I have never seen such a view.", "Please say that again.", "Are you still at work?",
  "Your bag is here.", "Where is the nearest hotel?", "Why are you laughing?", "Please wait while I check.", "Wash your hands before dinner.",
  "We walked through the park.", "The bank is between two shops.", "The cat is under the chair.", "We sat around the table.", "Our team played against theirs.",
  "Do not leave without your coat.", "It rained during the night.", "Please turn off the light.", "She walked down the stairs.", "The station is not far away.",
  "I always drink coffee in the morning.", "We often eat together.", "Sometimes I walk to work.", "He never arrives late.", "I am working from home today.",
  "We will meet again tomorrow.", "I saw her yesterday.", "The train has already left.", "Dinner will be ready soon.", "I will call you later.",
  // 150–199
  "We arrived early for the meeting.", "The bus was ten minutes late.", "It is a long journey.", "I have little free time today.", "Your answer is right.",
  "Turn left at the next street.", "They live in a big house.", "I need a small coffee.", "The shelf is too high.", "The table is quite low.",
  "This is an old photograph.", "She is still very young.", "This question is important.", "We have different ideas.", "The exercise is easy.",
  "Learning a language can be hard.", "We had a great holiday.", "The weather is bad today.", "This answer is better.", "That was the best day.",
  "Are you sure about that?", "Is it possible to change the date?", "She is able to help.", "This is a real problem.", "The story is true.",
  "Is this seat free?", "The bus is full.", "Please leave the window open.", "Please close the door.", "Dinner is ready.",
  "I feel happy today.", "The news made her sad.", "The child is afraid of dogs.", "I am tired after work.", "She is busy this morning.",
  "The garden is beautiful in spring.", "He is strong enough to lift it.", "Our new neighbour is very kind.", "Your explanation is clear.", "We have enough food for everyone.",
  "The man is waiting outside.", "The woman works at the hospital.", "The child is playing in the garden.", "The children are at school.", "My family lives nearby.",
  "I met a friend for lunch.", "My mother makes excellent soup.", "His father drives a bus.", "My brother is older than me.", "Her sister studies medicine.",
  // 200–249
  "Please write your name here.", "I am going home now.", "Their house has three bedrooms.", "My room is upstairs.", "Someone is at the door.",
  "Please open the window.", "This is a quiet place.", "People around the world use the internet.", "France is a beautiful country.", "We live in a small city.",
  "The street is very busy.", "The children walk to school.", "Every student needs a notebook.", "The teacher explained the question.", "She found a new job.",
  "He works for a large company.", "They started a small business.", "I left my keys at the office.", "We need money for the tickets.", "The price includes breakfast.",
  "The shop closes at six.", "We bought fruit at the market.", "The food is delicious.", "Could I have some water?", "I drink coffee every morning.",
  "Would you like a cup of tea?", "We need bread for breakfast.", "There is milk in the fridge.", "Fresh fruit is good for you.", "This vegetable is fresh.",
  "Breakfast is ready at seven.", "We had lunch at work.", "Dinner will be ready soon.", "My car is parked outside.", "The bus stops near my house.",
  "The train leaves at nine.", "This road leads to the airport.", "I love to travel by train.", "We took a trip to the mountains.", "They are on holiday in Italy.",
  "Our hotel is near the beach.", "We arrived at the airport early.", "I bought a ticket online.", "I am reading a good book.", "Your coffee is on the table.",
  "Please take a chair.", "The baby is asleep in bed.", "My phone needs charging.", "I use a computer at work.", "The internet is slow today.",
  // 250–299
  "I sent you an email yesterday.", "This picture shows my family.", "We listened to music all evening.", "That film was very funny.", "Would you like to play a game?",
  "Can I ask a question?", "I do not know the answer.", "That is a good idea.", "We need to solve this problem.", "What is the reason for the delay?",
  "She told us a funny story.", "I learned a new word today.", "English is an international language.", "Please write your phone number.", "This is the best part of the film.",
  "I forgot one important thing.", "Exercise is good for your life.", "Raise your hand if you know.", "My head hurts.", "Wash your face with cold water.",
  "Something is in my eye.", "The human body needs water.", "Walking is good for your health.", "You should see a doctor.", "It rained all night.",
  "I drink tea every morning.", "We went for a walk in the evening.", "I work five days a week.", "February is the shortest month.", "The journey takes one hour.",
  "Wait a minute, please.", "It was a very special moment.", "Start at the beginning.", "The film has a happy end.", "Children learn quickly at this age.",
  "Can you find my keys?", "Please tell me the truth.", "I need to ask you something.", "I feel much better today.", "Please try this cake.",
  "We leave for work at seven.", "I will call you this evening.", "Please keep the door closed.", "Let me help you.", "The lesson will begin soon.",
  "You seem tired today.", "Can I help you?", "We need to talk.", "Turn right at the corner.", "The meeting will start at ten.",
  // 300–349
  "Can you show me the way?", "I can hear music outside.", "The children play in the garden.", "I run in the park every morning.", "Please move your chair.",
  "They live in Switzerland.", "I believe your story.", "Please bring your passport.", "Accidents can happen quickly.", "Write your address here.",
  "We provide free information.", "Please sit next to me.", "Please stand over here.", "Do not lose your ticket.", "Can I pay by card?",
  "Let us meet after work.", "The price does not include drinks.", "Please continue with your story.", "Set the bag on the floor.", "I want to learn English.",
  "Plans can change quickly.", "This road will lead you home.", "I understand the question now.", "We watch the news every evening.", "Please follow me.",
  "The bus will stop here.", "They want to create a new website.", "Please speak more slowly.", "I read before I go to sleep.", "They do not allow pets here.",
  "Please add some salt.", "We spend weekends with our family.", "Tomatoes grow well here.", "I walk to the office.", "Our team hopes to win.",
  "They offer free coffee.", "Remember to lock the door.", "I love this song.", "Please consider my idea.", "A rainbow may appear after the rain.",
  "I need to buy some bread.", "Please wait outside.", "They serve breakfast until ten.", "Plants die without water.", "Please send me the address.",
  // 350–399
  "We expect the train at noon.", "They plan to build a new school.", "Please stay here.", "Leaves fall in autumn.", "Be careful when you cut the bread.",
  "We should reach the hotel by six.", "We eat dinner together.", "Remember to drink enough water.", "I usually sleep for eight hours.", "Can you drive a car?",
  "You can choose any colour.", "Wear a warm coat outside.", "Wash your hands before eating.", "I cook dinner every evening.", "I need your help.",
  "She wants to become a doctor.", "Put the book on the table.", "What does this word mean?", "I will return tomorrow.", "Can you explain this rule?",
  "I hope you feel better soon.", "We need to decide today.", "Can you carry this bag?", "Be careful not to break the glass.", "Did you receive my email?",
  "I agree with you.", "They sell fresh bread here.", "I hope I pass the test.", "Do not forget your keys.", "Please listen carefully.",
  "The person at the desk can help.", "Our group meets every Tuesday.", "She works well in a team.", "Every parent worries sometimes.", "The baby is sleeping.",
  "The boy is riding a bicycle.", "The girl has a red jacket.", "Our new neighbor is friendly.", "The customer asked for help.", "Call the police in an emergency.",
  "We need more information.", "I watch the news every evening.", "Can you give me an example?", "That is an interesting fact.", "You have a good point.",
  // 400–449
  "Please stand by my side.", "Write your name on this line.", "This area is very quiet.", "Meet me in the city center.", "This course is for every level.",
  "I am happy with the result.",
  "The hotel offers excellent service.", "We need a clear plan.", "The project finishes next month.", "This computer program is free.", "I am taking an English course.",
  "We have a test tomorrow.", "Write the answer on the paper.", "I received a letter from Anna.", "Can you show me the map?", "Blue is my favourite color.",
  "Please turn on the light.", "Open the window for some fresh air.", "The fire kept us warm.", "The earth moves around the sun.", "The weather is lovely today.",
  "The rain stopped this morning.", "The sun is shining.", "There is a bird in the tree.", "Every animal needs water.", "The dog is sleeping by the door.",
  "Our cat likes warm places.", "We grow flowers in the garden.", "What is today's date?", "Spring is my favourite season.", "The flowers open in spring.",
  "We go swimming in summer.", "The leaves change colour in autumn.", "It often snows in winter.", "The wind comes from the north.", "They travelled south for the winter.",
  "The sun rises in the east.", "The sun sets in the west.", "It is warm inside the house.", "The children are playing outside.", "The picture hangs above the bed.",
  "The shoes are below the shelf.", "The station is near our hotel.", "The airport is far from here.", "We cooked dinner together.", "Maybe we can meet tomorrow.",
  "I really enjoyed the film.", "Dinner is almost ready.", "I like fruit, especially apples.", "The train will probably be late.", "I usually walk to work.",
  // 450–499
  "Please finish the work quickly.", "Drive slowly in the village.", "Please read the question carefully.", "That is exactly what I meant.", "Yes, I would like some coffee.",
  "Please close the window.", "Thanks for your help.", "Sorry, I am late.", "Hello, my name is Anna.", "We said goodbye at the station.",
  "She is wearing a red coat.", "The sky is blue today.", "The grass is green.", "He has a black car.", "The walls are white.",
  "The soup is very hot.", "My hands are cold.", "Keep the food warm.", "The kitchen is clean.", "Your shoes are dirty.",
  "This train is very fast.", "The service is quite slow.", "The tickets were cheap.", "That restaurant is expensive.", "The country is rich in history.",
  "The family was poor but happy.", "This is a safe place.", "Driving too fast is dangerous.", "Fresh food keeps you healthy.", "I stayed home because I was sick.",
  "I am hungry after the walk.", "Are you thirsty?", "The book is very interesting.", "The lesson was boring.", "Have a nice day!",
  "Our neighbours are friendly.", "The street is quiet at night.", "The music is too loud.", "Your answer is correct.", "That phone number is wrong.",
  "I would like a single room.", "They have been married for ten years.", "Today is a special day.", "This is completely normal.", "The park is open to the public.",
  "This is a private conversation.", "Is this room available tonight?", "Water is necessary for life.", "I am certain that she called.", "I have three questions.",
  "The table has four legs.", "We waited for five minutes.", "The shop closes at six.", "She gets up at seven.", "I sleep for eight hours.",
  "The train leaves at nine.", "There are ten students here.", "The meeting starts at eleven.", "Lunch is served at twelve.",
];
