export type DailyWord = readonly [
  english: string,
  german: string,
  example: string,
  category?: string,
  status?: "new" | "learning" | "learned",
  favorite?: boolean,
];

// Die 103 Karten aus der ursprünglichen persönlichen Sammlung und der
// Alltagssatz-Liste. Sie werden beim ersten Start mit den 1.000 bestehenden
// Karten zusammengeführt, ohne den persönlichen Lernstand zu überschreiben.
export const dailyWords: DailyWord[] = [
  ["to figure out", "herausfinden, verstehen", "I need to figure out how this works.", "Alltag", "learning", true],
  ["remarkable", "bemerkenswert", "She made remarkable progress.", "Arbeit"],
  ["eventually", "schliesslich, letztendlich", "Eventually, everything fell into place.", "Alltag", "learned"],
  ["Good morning!", "Guten Morgen!", "Good morning! Did you sleep well?"],
  ["How are you?", "Wie geht es dir?", "Hi Anna, how are you today?"],
  ["I'm fine, thank you.", "Mir geht es gut, danke.", "I'm fine, thank you. And you?"],
  ["Could you help me, please?", "Könntest du mir bitte helfen?", "Could you help me, please? I can't find the station."],
  ["Where is the bathroom?", "Wo ist die Toilette?", "Excuse me, where is the bathroom?"],
  ["How much does this cost?", "Wie viel kostet das?", "I like this shirt. How much does this cost?"],
  ["I would like a coffee, please.", "Ich hätte gerne einen Kaffee.", "I would like a coffee, please, with a little milk."],
  ["What time is it?", "Wie spät ist es?", "Sorry, what time is it?"],
  ["See you later.", "Bis später.", "I have to go now. See you later."],
  ["Have a nice day!", "Schönen Tag noch!", "Thank you for your help. Have a nice day!"],
  ["Please sit down.", "Bitte setzen Sie sich.", "Please sit down."],
  ["Please wait a moment.", "Bitte warten Sie einen Moment.", "Please wait a moment."],
  ["I don't understand.", "Ich verstehe nicht.", "I don't understand."],
  ["Could you repeat that?", "Könnten Sie das wiederholen?", "Could you repeat that?"],
  ["Please speak more slowly.", "Bitte sprechen Sie langsamer.", "Please speak more slowly."],
  ["What does this mean?", "Was bedeutet das?", "What does this mean?"],
  ["How do you spell that?", "Wie schreibt man das?", "How do you spell that?"],
  ["Can you show me?", "Kannst du es mir zeigen?", "Can you show me?"],
  ["I am learning English.", "Ich lerne Englisch.", "I am learning English."],
  ["My name is Alex.", "Ich heisse Alex.", "My name is Alex."],
  ["Nice to meet you.", "Schön, dich kennenzulernen.", "Nice to meet you."],
  ["Where are you from?", "Woher kommst du?", "Where are you from?"],
  ["I am from Switzerland.", "Ich komme aus der Schweiz.", "I am from Switzerland."],
  ["Do you speak German?", "Sprichst du Deutsch?", "Do you speak German?"],
  ["I live nearby.", "Ich wohne in der Nähe.", "I live nearby."],
  ["I am at home.", "Ich bin zu Hause.", "I am at home."],
  ["I am going to work.", "Ich gehe zur Arbeit.", "I am going to work."],
  ["I am on my way.", "Ich bin unterwegs.", "I am on my way."],
  ["I am running late.", "Ich verspäte mich.", "I am running late."],
  ["I will be there soon.", "Ich werde bald da sein.", "I will be there soon."],
  ["Let's go.", "Lass uns gehen.", "Let's go."],
  ["Come with me.", "Komm mit mir.", "Come with me."],
  ["Wait for me.", "Warte auf mich.", "Wait for me."],
  ["Be careful.", "Sei vorsichtig.", "Be careful."],
  ["No problem.", "Kein Problem.", "No problem."],
  ["That's a good idea.", "Das ist eine gute Idee.", "That's a good idea."],
  ["I don't know.", "Ich weiss es nicht.", "I don't know."],
  ["I think so.", "Ich denke schon.", "I think so."],
  ["I don't think so.", "Ich glaube nicht.", "I don't think so."],
  ["Maybe later.", "Vielleicht später.", "Maybe later."],
  ["Of course.", "Natürlich.", "Of course."],
  ["That's okay.", "Das ist in Ordnung.", "That's okay."],
  ["It doesn't matter.", "Das macht nichts.", "It doesn't matter."],
  ["I'm sorry.", "Es tut mir leid.", "I'm sorry."],
  ["Excuse me.", "Entschuldigung.", "Excuse me."],
  ["Thank you very much.", "Vielen Dank.", "Thank you very much."],
  ["You're welcome.", "Gern geschehen.", "You're welcome."],
  ["Can I have the bill, please?", "Kann ich bitte die Rechnung haben?", "Can I have the bill, please?"],
  ["A table for two, please.", "Einen Tisch für zwei, bitte.", "A table for two, please."],
  ["The food is delicious.", "Das Essen ist köstlich.", "The food is delicious."],
  ["I'm hungry.", "Ich habe Hunger.", "I'm hungry."],
  ["I'm thirsty.", "Ich habe Durst.", "I'm thirsty."],
  ["I'd like some water.", "Ich hätte gerne etwas Wasser.", "I'd like some water."],
  ["Do you have a menu?", "Haben Sie eine Speisekarte?", "Do you have a menu?"],
  ["Is this seat free?", "Ist dieser Platz frei?", "Is this seat free?"],
  ["Where is the bus stop?", "Wo ist die Bushaltestelle?", "Where is the bus stop?"],
  ["Which bus goes to the city centre?", "Welcher Bus fährt ins Stadtzentrum?", "Which bus goes to the city centre?"],
  ["When does the train leave?", "Wann fährt der Zug ab?", "When does the train leave?"],
  ["I need a ticket.", "Ich brauche eine Fahrkarte.", "I need a ticket."],
  ["How long does it take?", "Wie lange dauert es?", "How long does it take?"],
  ["Is it far from here?", "Ist es weit von hier?", "Is it far from here?"],
  ["Turn left.", "Biegen Sie links ab.", "Turn left."],
  ["Turn right.", "Biegen Sie rechts ab.", "Turn right."],
  ["Go straight ahead.", "Gehen Sie geradeaus.", "Go straight ahead."],
  ["I'm lost.", "Ich habe mich verirrt.", "I'm lost."],
  ["Can you call a taxi?", "Können Sie ein Taxi rufen?", "Can you call a taxi?"],
  ["Please take me to this address.", "Bitte bringen Sie mich zu dieser Adresse.", "Please take me to this address."],
  ["Can I pay by card?", "Kann ich mit Karte bezahlen?", "Can I pay by card?"],
  ["Do you have change?", "Haben Sie Wechselgeld?", "Do you have change?"],
  ["That's too expensive.", "Das ist zu teuer.", "That's too expensive."],
  ["I'm just looking.", "Ich schaue mich nur um.", "I'm just looking."],
  ["I'd like to buy this.", "Ich möchte das kaufen.", "I'd like to buy this."],
  ["Do you have a smaller size?", "Haben Sie eine kleinere Grösse?", "Do you have a smaller size?"],
  ["Can I try this on?", "Kann ich das anprobieren?", "Can I try this on?"],
  ["Where is the changing room?", "Wo ist die Umkleidekabine?", "Where is the changing room?"],
  ["I'm tired.", "Ich bin müde.", "I'm tired."],
  ["I need a break.", "Ich brauche eine Pause.", "I need a break."],
  ["I don't feel well.", "Ich fühle mich nicht gut.", "I don't feel well."],
  ["I have a headache.", "Ich habe Kopfschmerzen.", "I have a headache."],
  ["Can you open the window?", "Kannst du das Fenster öffnen?", "Can you open the window?"],
  ["Please close the door.", "Bitte schliess die Tür.", "Please close the door."],
  ["It's cold today.", "Heute ist es kalt.", "It's cold today."],
  ["It's very hot.", "Es ist sehr heiss.", "It's very hot."],
  ["It looks like rain.", "Es sieht nach Regen aus.", "It looks like rain."],
  ["What's the weather like?", "Wie ist das Wetter?", "What's the weather like?"],
  ["What are you doing?", "Was machst du?", "What are you doing?"],
  ["I'm cooking dinner.", "Ich koche das Abendessen.", "I'm cooking dinner."],
  ["I'm cleaning the house.", "Ich putze das Haus.", "I'm cleaning the house."],
  ["I'm going shopping.", "Ich gehe einkaufen.", "I'm going shopping."],
  ["I need to buy groceries.", "Ich muss Lebensmittel kaufen.", "I need to buy groceries."],
  ["Where are my keys?", "Wo sind meine Schlüssel?", "Where are my keys?"],
  ["I can't find my phone.", "Ich kann mein Handy nicht finden.", "I can't find my phone."],
  ["The battery is empty.", "Der Akku ist leer.", "The battery is empty."],
  ["Can I use your charger?", "Kann ich dein Ladegerät benutzen?", "Can I use your charger?"],
  ["I'll call you later.", "Ich rufe dich später an.", "I'll call you later."],
  ["Send me a message.", "Schick mir eine Nachricht.", "Send me a message."],
  ["What are your plans?", "Was hast du vor?", "What are your plans?"],
  ["Are you free tonight?", "Hast du heute Abend Zeit?", "Are you free tonight?"],
  ["Let's meet tomorrow.", "Lass uns morgen treffen.", "Let's meet tomorrow."],
  ["See you tomorrow.", "Bis morgen.", "See you tomorrow."],
];
