export type LanguageIslandLine = readonly [
  topic: string,
  english: string,
  german: string,
  replyEnglish: string,
  replyGerman: string,
];

export const languageIslandLines: readonly LanguageIslandLine[] = [
  ["Restaurantbesuch", "Good evening. Do you have a table for two?", "Guten Abend. Haben Sie einen Tisch für zwei Personen?", "Certainly. Please follow me.", "Natürlich. Bitte folgen Sie mir."],
  ["Restaurantbesuch", "Could we have a table by the window?", "Könnten wir einen Tisch am Fenster haben?", "I will see what I can do.", "Ich werde sehen, was ich tun kann."],
  ["Restaurantbesuch", "Could we see the menu, please?", "Könnten wir bitte die Speisekarte sehen?", "Of course. Here are the menus.", "Natürlich. Hier sind die Speisekarten."],
  ["Restaurantbesuch", "Do you have a menu in English?", "Haben Sie eine Speisekarte auf Englisch?", "Yes, I will bring you one.", "Ja, ich bringe Ihnen eine."],
  ["Restaurantbesuch", "What is today's special?", "Was ist das heutige Tagesgericht?", "Today's special is grilled salmon with vegetables.", "Das heutige Tagesgericht ist gegrillter Lachs mit Gemüse."],
  ["Restaurantbesuch", "Could you give us a few more minutes?", "Könnten Sie uns noch ein paar Minuten geben?", "No problem. I will come back shortly.", "Kein Problem. Ich komme gleich wieder."],
  ["Restaurantbesuch", "Are you ready to order?", "Sind Sie bereit zu bestellen?", "Yes, I would like the tomato soup to start.", "Ja, ich hätte gerne zuerst die Tomatensuppe."],
  ["Restaurantbesuch", "What would you like for the main course?", "Was möchten Sie als Hauptgericht?", "I will have the grilled chicken, please.", "Ich nehme bitte das gegrillte Poulet."],
  ["Restaurantbesuch", "What do you recommend?", "Was können Sie empfehlen?", "The pasta is very popular with our guests.", "Die Pasta ist bei unseren Gästen sehr beliebt."],
  ["Restaurantbesuch", "What does this dish come with?", "Welche Beilagen gehören zu diesem Gericht?", "It comes with rice and seasonal vegetables.", "Es wird mit Reis und saisonalem Gemüse serviert."],
  ["Restaurantbesuch", "Could I have the salad instead of the fries?", "Könnte ich den Salat statt der Pommes haben?", "Yes, that is no problem.", "Ja, das ist kein Problem."],
  ["Restaurantbesuch", "I am vegetarian. Which dishes can I eat?", "Ich bin Vegetarier. Welche Gerichte kann ich essen?", "The vegetable curry and the pasta are vegetarian.", "Das Gemüsecurry und die Pasta sind vegetarisch."],
  ["Restaurantbesuch", "Does this dish contain any nuts?", "Enthält dieses Gericht Nüsse?", "I will check with the kitchen for you.", "Ich frage für Sie in der Küche nach."],
  ["Restaurantbesuch", "I am allergic to dairy products.", "Ich bin allergisch gegen Milchprodukte.", "Thank you for telling us. We will inform the kitchen.", "Danke, dass Sie uns das sagen. Wir informieren die Küche."],
  ["Restaurantbesuch", "Could you make it less spicy, please?", "Könnten Sie es bitte weniger scharf zubereiten?", "Certainly. I will let the chef know.", "Natürlich. Ich sage dem Koch Bescheid."],
  ["Restaurantbesuch", "Could we have a bottle of still water?", "Könnten wir eine Flasche Wasser ohne Kohlensäure haben?", "Would you like it chilled or at room temperature?", "Möchten Sie es gekühlt oder bei Zimmertemperatur?"],
  ["Restaurantbesuch", "I would like a glass of red wine, please.", "Ich hätte gerne ein Glas Rotwein.", "Would you prefer a dry or a fruity wine?", "Möchten Sie lieber einen trockenen oder einen fruchtigen Wein?"],
  ["Restaurantbesuch", "Excuse me, could we have some more bread?", "Entschuldigung, könnten wir noch etwas Brot haben?", "Of course. I will bring some right away.", "Natürlich. Ich bringe Ihnen sofort welches."],
  ["Restaurantbesuch", "Everything is delicious, thank you.", "Alles ist köstlich, vielen Dank.", "I am glad you are enjoying it.", "Es freut mich, dass es Ihnen schmeckt."],
  ["Restaurantbesuch", "Excuse me, my food is cold.", "Entschuldigung, mein Essen ist kalt.", "I am sorry. I will have it warmed up immediately.", "Das tut mir leid. Ich lasse es sofort aufwärmen."],
  ["Restaurantbesuch", "I ordered the fish, not the chicken.", "Ich habe den Fisch bestellt, nicht das Poulet.", "I apologize. I will correct the order right away.", "Ich entschuldige mich. Ich werde die Bestellung sofort korrigieren."],
  ["Restaurantbesuch", "Could we order dessert?", "Könnten wir ein Dessert bestellen?", "Certainly. Would you like to see the dessert menu?", "Natürlich. Möchten Sie die Dessertkarte sehen?"],
  ["Restaurantbesuch", "Could I have a coffee, please?", "Könnte ich bitte einen Kaffee haben?", "Certainly. Would you like milk or sugar with it?", "Natürlich. Möchten Sie Milch oder Zucker dazu?"],
  ["Restaurantbesuch", "Could we have the bill, please?", "Könnten wir bitte die Rechnung haben?", "Of course. I will bring it right away.", "Natürlich. Ich bringe sie sofort."],
  ["Restaurantbesuch", "Is service included?", "Ist der Service inbegriffen?", "Yes, service is included in the bill.", "Ja, der Service ist in der Rechnung inbegriffen."],
  ["Restaurantbesuch", "Can I pay by card?", "Kann ich mit Karte bezahlen?", "Yes, we accept all major cards.", "Ja, wir akzeptieren alle gängigen Karten."],
  ["Restaurantbesuch", "Could we split the bill, please?", "Könnten wir die Rechnung bitte aufteilen?", "Certainly. How would you like to divide it?", "Natürlich. Wie möchten Sie sie aufteilen?"],
  ["Restaurantbesuch", "Please keep the change.", "Der Rest ist für Sie.", "Thank you very much.", "Vielen Dank."],
  ["Restaurantbesuch", "The meal was excellent.", "Das Essen war ausgezeichnet.", "Thank you. We hope to see you again soon.", "Vielen Dank. Wir hoffen, Sie bald wiederzusehen."],
  ["Restaurantbesuch", "Thank you. Have a nice evening.", "Vielen Dank. Einen schönen Abend noch.", "You too. Goodbye!", "Ihnen auch. Auf Wiedersehen!"],
  ["Hotel", "Hello. I have a reservation under the name Müller.", "Guten Tag. Ich habe eine Reservierung auf den Namen Müller.", "Welcome, Mr Müller. May I see your passport, please?", "Willkommen, Herr Müller. Darf ich bitte Ihren Pass sehen?"],
  ["Hotel", "I would like to book a room for three nights.", "Ich möchte ein Zimmer für drei Nächte buchen.", "Certainly. What dates will you be staying with us?", "Gerne. An welchen Daten werden Sie bei uns übernachten?"],
  ["Hotel", "Do you have a double room available?", "Haben Sie ein Doppelzimmer frei?", "Yes, we have one available on the second floor.", "Ja, wir haben eines im zweiten Stock frei."],
  ["Hotel", "How much is the room per night?", "Wie viel kostet das Zimmer pro Nacht?", "It is 160 francs per night, including breakfast.", "Es kostet 160 Franken pro Nacht, inklusive Frühstück."],
  ["Hotel", "Is breakfast included in the price?", "Ist das Frühstück im Preis inbegriffen?", "Yes, breakfast is included in your booking.", "Ja, das Frühstück ist in Ihrer Buchung inbegriffen."],
  ["Hotel", "Could I have a quiet room, please?", "Könnte ich bitte ein ruhiges Zimmer haben?", "Of course. I will give you a room facing the courtyard.", "Natürlich. Ich gebe Ihnen ein Zimmer zum Innenhof."],
  ["Hotel", "Could I have a room with a view?", "Könnte ich ein Zimmer mit Aussicht haben?", "Let me check what is available.", "Ich prüfe, was verfügbar ist."],
  ["Hotel", "What time is check-in?", "Ab wann kann ich einchecken?", "Check-in is from three o'clock in the afternoon.", "Der Check-in ist ab drei Uhr nachmittags möglich."],
  ["Hotel", "Can I leave my luggage here before check-in?", "Kann ich mein Gepäck vor dem Check-in hier lassen?", "Certainly. We can store it for you at reception.", "Natürlich. Wir können es an der Rezeption für Sie aufbewahren."],
  ["Hotel", "Is the room ready yet?", "Ist das Zimmer schon bereit?", "It will be ready in about twenty minutes.", "Es wird in etwa zwanzig Minuten bereit sein."],
  ["Hotel", "Could you tell me my room number?", "Könnten Sie mir meine Zimmernummer sagen?", "You are in room 214 on the second floor.", "Sie sind in Zimmer 214 im zweiten Stock."],
  ["Hotel", "How do I get to my room?", "Wie komme ich zu meinem Zimmer?", "Take the lift to the second floor and turn left.", "Nehmen Sie den Lift in den zweiten Stock und biegen Sie links ab."],
  ["Hotel", "Could I have another key card, please?", "Könnte ich bitte eine weitere Schlüsselkarte haben?", "Certainly. I will make one for you now.", "Natürlich. Ich stelle Ihnen sofort eine aus."],
  ["Hotel", "What is the Wi-Fi password?", "Wie lautet das WLAN-Passwort?", "The password is written on your key-card holder.", "Das Passwort steht auf Ihrer Schlüsselkartenhülle."],
  ["Hotel", "What time is breakfast served?", "Wann wird das Frühstück serviert?", "Breakfast is served from seven until ten.", "Das Frühstück wird von sieben bis zehn Uhr serviert."],
  ["Hotel", "Where is the breakfast room?", "Wo ist der Frühstücksraum?", "It is on the ground floor next to reception.", "Er befindet sich im Erdgeschoss neben der Rezeption."],
  ["Hotel", "Is there a gym in the hotel?", "Gibt es im Hotel einen Fitnessraum?", "Yes, it is open around the clock.", "Ja, er ist rund um die Uhr geöffnet."],
  ["Hotel", "Could you order a taxi for me?", "Könnten Sie mir ein Taxi bestellen?", "Of course. What time do you need it?", "Natürlich. Um welche Uhrzeit benötigen Sie es?"],
  ["Hotel", "Could I get an extra towel, please?", "Könnte ich bitte ein zusätzliches Handtuch bekommen?", "Certainly. Housekeeping will bring one to your room.", "Natürlich. Der Zimmerservice bringt Ihnen eines aufs Zimmer."],
  ["Hotel", "Could you clean my room later today?", "Könnten Sie mein Zimmer heute später reinigen?", "Yes, I will inform housekeeping.", "Ja, ich informiere den Zimmerservice."],
  ["Hotel", "The air conditioning is not working.", "Die Klimaanlage funktioniert nicht.", "I am sorry. We will send someone to check it.", "Das tut mir leid. Wir schicken jemanden, der sie überprüft."],
  ["Hotel", "There is no hot water in my room.", "In meinem Zimmer gibt es kein warmes Wasser.", "I apologize. We will look into it immediately.", "Ich entschuldige mich. Wir kümmern uns sofort darum."],
  ["Hotel", "The room is too noisy.", "Das Zimmer ist zu laut.", "I am sorry. We can offer you a quieter room.", "Das tut mir leid. Wir können Ihnen ein ruhigeres Zimmer anbieten."],
  ["Hotel", "I think I left my phone in the lobby.", "Ich glaube, ich habe mein Handy in der Lobby liegen lassen.", "I will check with lost and found for you.", "Ich frage für Sie beim Fundbüro nach."],
  ["Hotel", "Can you recommend a good restaurant nearby?", "Können Sie ein gutes Restaurant in der Nähe empfehlen?", "Certainly. There is an excellent local restaurant around the corner.", "Natürlich. Gleich um die Ecke gibt es ein ausgezeichnetes lokales Restaurant."],
  ["Hotel", "Could you book a table for two?", "Könnten Sie einen Tisch für zwei Personen reservieren?", "Of course. What time would you prefer?", "Natürlich. Welche Uhrzeit wäre Ihnen am liebsten?"],
  ["Hotel", "What time is check-out?", "Bis wann muss ich auschecken?", "Check-out is by eleven o'clock.", "Der Check-out ist bis elf Uhr."],
  ["Hotel", "Could I check out a little later?", "Könnte ich etwas später auschecken?", "We can offer you a late check-out until one o'clock.", "Wir können Ihnen einen späten Check-out bis ein Uhr anbieten."],
  ["Hotel", "Could I have the bill, please?", "Könnte ich bitte die Rechnung haben?", "Certainly. Would you like to pay by card or in cash?", "Natürlich. Möchten Sie mit Karte oder bar bezahlen?"],
  ["Hotel", "Can you store my luggage after check-out?", "Können Sie mein Gepäck nach dem Check-out aufbewahren?", "Of course. You can collect it later today.", "Natürlich. Sie können es später heute abholen."],
];
