export type LanguageIslandLine = readonly [
  topic: string,
  english: string,
  german: string,
  replyEnglish: string,
  replyGerman: string,
];

export const languageIslandLines: readonly LanguageIslandLine[] = [
  ["Restaurantbesuch", "Good evening. Do you have a table for two?", "Guten Abend. Haben Sie einen Tisch für zwei Personen?", "Certainly. Please follow me.", "Natürlich. Bitte folgen Sie mir."],
  ["Restaurantbesuch", "Could we have a table by the window?", "Könnten wir einen Tisch am Fenster haben?", "I will see what I can do.", "Ich werde sehen, was ich tun kann."],
  ["Restaurantbesuch", "Could we see the menu, please?", "Könnten wir bitte die Speisekarte sehen?", "Of course. Here are the menus.", "Natürlich. Hier sind die Speisekarten."],
  ["Restaurantbesuch", "Do you have a menu in English?", "Haben Sie eine Speisekarte auf Englisch?", "Yes, I will bring you one.", "Ja, ich bringe Ihnen eine."],
  ["Restaurantbesuch", "What is today's special?", "Was ist das heutige Tagesgericht?", "Today's special is grilled salmon with vegetables.", "Das heutige Tagesgericht ist gegrillter Lachs mit Gemüse."],
  ["Restaurantbesuch", "Could you give us a few more minutes?", "Könnten Sie uns noch ein paar Minuten geben?", "No problem. I will come back shortly.", "Kein Problem. Ich komme gleich wieder."],
  ["Restaurantbesuch", "Are you ready to order?", "Sind Sie bereit zu bestellen?", "Yes, I would like the tomato soup to start.", "Ja, ich hätte gerne zuerst die Tomatensuppe."],
  ["Restaurantbesuch", "What would you like for the main course?", "Was möchten Sie als Hauptgericht?", "I will have the grilled chicken, please.", "Ich nehme bitte das gegrillte Poulet."],
  ["Restaurantbesuch", "What do you recommend?", "Was können Sie empfehlen?", "The pasta is very popular with our guests.", "Die Pasta ist bei unseren Gästen sehr beliebt."],
  ["Restaurantbesuch", "What does this dish come with?", "Welche Beilagen gehören zu diesem Gericht?", "It comes with rice and seasonal vegetables.", "Es wird mit Reis und saisonalem Gemüse serviert."],
  ["Restaurantbesuch", "Could I have the salad instead of the fries?", "Könnte ich den Salat statt der Pommes haben?", "Yes, that is no problem.", "Ja, das ist kein Problem."],
  ["Restaurantbesuch", "I am vegetarian. Which dishes can I eat?", "Ich bin Vegetarier. Welche Gerichte kann ich essen?", "The vegetable curry and the pasta are vegetarian.", "Das Gemüsecurry und die Pasta sind vegetarisch."],
  ["Restaurantbesuch", "Does this dish contain any nuts?", "Enthält dieses Gericht Nüsse?", "I will check with the kitchen for you.", "Ich frage für Sie in der Küche nach."],
  ["Restaurantbesuch", "I am allergic to dairy products.", "Ich bin allergisch gegen Milchprodukte.", "Thank you for telling us. We will inform the kitchen.", "Danke, dass Sie uns das sagen. Wir informieren die Küche."],
  ["Restaurantbesuch", "Could you make it less spicy, please?", "Könnten Sie es bitte weniger scharf zubereiten?", "Certainly. I will let the chef know.", "Natürlich. Ich sage dem Koch Bescheid."],
  ["Restaurantbesuch", "Could we have a bottle of still water?", "Könnten wir eine Flasche Wasser ohne Kohlensäure haben?", "Would you like it chilled or at room temperature?", "Möchten Sie es gekühlt oder bei Zimmertemperatur?"],
  ["Restaurantbesuch", "I would like a glass of red wine, please.", "Ich hätte gerne ein Glas Rotwein.", "Would you prefer a dry or a fruity wine?", "Möchten Sie lieber einen trockenen oder einen fruchtigen Wein?"],
  ["Restaurantbesuch", "Excuse me, could we have some more bread?", "Entschuldigung, könnten wir noch etwas Brot haben?", "Of course. I will bring some right away.", "Natürlich. Ich bringe Ihnen sofort welches."],
  ["Restaurantbesuch", "Everything is delicious, thank you.", "Alles ist köstlich, vielen Dank.", "I am glad you are enjoying it.", "Es freut mich, dass es Ihnen schmeckt."],
  ["Restaurantbesuch", "Excuse me, my food is cold.", "Entschuldigung, mein Essen ist kalt.", "I am sorry. I will have it warmed up immediately.", "Das tut mir leid. Ich lasse es sofort aufwärmen."],
  ["Restaurantbesuch", "I ordered the fish, not the chicken.", "Ich habe den Fisch bestellt, nicht das Poulet.", "I apologize. I will correct the order right away.", "Ich entschuldige mich. Ich werde die Bestellung sofort korrigieren."],
  ["Restaurantbesuch", "Could we order dessert?", "Könnten wir ein Dessert bestellen?", "Certainly. Would you like to see the dessert menu?", "Natürlich. Möchten Sie die Dessertkarte sehen?"],
  ["Restaurantbesuch", "Could I have a coffee, please?", "Könnte ich bitte einen Kaffee haben?", "Certainly. Would you like milk or sugar with it?", "Natürlich. Möchten Sie Milch oder Zucker dazu?"],
  ["Restaurantbesuch", "Could we have the bill, please?", "Könnten wir bitte die Rechnung haben?", "Of course. I will bring it right away.", "Natürlich. Ich bringe sie sofort."],
  ["Restaurantbesuch", "Is service included?", "Ist der Service inbegriffen?", "Yes, service is included in the bill.", "Ja, der Service ist in der Rechnung inbegriffen."],
  ["Restaurantbesuch", "Can I pay by card?", "Kann ich mit Karte bezahlen?", "Yes, we accept all major cards.", "Ja, wir akzeptieren alle gängigen Karten."],
  ["Restaurantbesuch", "Could we split the bill, please?", "Könnten wir die Rechnung bitte aufteilen?", "Certainly. How would you like to divide it?", "Natürlich. Wie möchten Sie sie aufteilen?"],
  ["Restaurantbesuch", "Please keep the change.", "Der Rest ist für Sie.", "Thank you very much.", "Vielen Dank."],
  ["Restaurantbesuch", "The meal was excellent.", "Das Essen war ausgezeichnet.", "Thank you. We hope to see you again soon.", "Vielen Dank. Wir hoffen, Sie bald wiederzusehen."],
  ["Restaurantbesuch", "Thank you. Have a nice evening.", "Vielen Dank. Einen schönen Abend noch.", "You too. Goodbye!", "Ihnen auch. Auf Wiedersehen!"],
];
